### ISSUE TITLE
Could not find class

### ISSUE THREAD

**Issue by SPQRInc** [sensson/puppet-csf#1]
Hello,

I installed the module this way:

```
sensson-csf/
├── manifests
│   ├── allow.pp
│   ├── config.pp
│   ├── deny.pp
│   ├── global.pp
│   ├── ignore.pp
│   ├── init.pp
│   ├── install.pp
│   ├── ipv4
│   │   ├── input.pp
│   │   └── output.pp
│   └── rule.pp
├── metadata.json
├── README.md
└── templates
    ├── csf.conf.rb
    ├── csf_header.rb
    ├── csf_rule.rb
    └── csf_vpn.rb

```

Now I'm getting this error:

`Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not find class csf for pp-example.example.com on node pp-example.example.com
`

Any idea how to change this?

**Comment by sensson** [comment]
Sorry for the delay. If you rename the module's folder from sensson-csf to csf it should work.
