### ISSUE TITLE
Question/help around the CSF-Docker script

### ISSUE THREAD

**Issue by MaybeThisIsRu** [sensson/puppet-csf#17]
Hi!

I'm new to CSF and Docker's been giving me a nightmare. Looking through your CSF Docker script (the *only* one to have worked so far -- thank you), I'm wondering why doing what [the script says here](https://github.com/sensson/puppet-csf/blob/master/templates/csf_docker.sh) is necessary or recommended:

> Make sure to disable Docker's iptables management with --iptables=false.

I'd appreciate any pointers. *Not* disabling Docker's iptables autoconfiguration *and* having this script run for CSF still seems to work in my very, very elementary testing. Would this introduce potential bugs, or worse, security issues?

**Comment by ju5t** [comment]
Not that we know. We made this before Docker support was added to CSF. I would recommend using that instead.

**Comment by MaybeThisIsRu** [comment]
Ah, okay. I'm having issues with the in-built support on Ubuntu 20.04, which is how I ended up here.

Anyway, thanks for your perspective! 😊

**Comment by ju5t** [comment]
No worries, good luck!
